---
groups:
  - name: test
    rules:
      - alert: PrometheusTargetMissingWithWarmupTime
        expr: sum by (instance, job) ((up == 0) * on (instance) group_left(__name__) (node_time_seconds - node_boot_time_seconds > 600))
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: Prometheus target missing with warmup time (instance {{ $labels.instance }})
          description: "Allow a job time to start up (10 minutes) before alerting that it's down.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"