name: Run promtool
on:
  workflow_call:

jobs:
  promtool:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Check Prometheus Alert Rules
        uses: peimanja/promtool-github-actions@master
        with:
          promtool_actions_subcommand: 'rules'
          promtool_actions_files: 'prometheus/alert_rules/*.yaml'
          promtool_actions_version: '2.14.0'
          promtool_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # repeat the above actions for different promtool subcommands